import { randomUUID } from "node:crypto";
import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { customAlphabet } from "nanoid";
import {
  canViewVideo,
  VISIBILITIES,
  type Role,
  type Visibility,
} from "@play/shared";
import { importQueue, trimQueue } from "@play/worker/queue";
import { config, removeObject } from "@play/storage";
import { router, publicProcedure, protectedProcedure } from "../init";

const captionsRouter = router({
  list: publicProcedure
    .input(z.object({ videoId: z.string().min(1) }))
    .query(async ({ ctx, input }) => {
      return ctx.prisma.videoCaption.findMany({
        where: { videoId: input.videoId },
        orderBy: [{ isDefault: "desc" }, { language: "asc" }],
        select: {
          id: true,
          language: true,
          label: true,
          assetKey: true,
          isDefault: true,
          isAutoGenerated: true,
        },
      });
    }),

  remove: protectedProcedure
    .input(z.object({ captionId: z.string().min(1) }))
    .mutation(async ({ ctx, input }) => {
      const sessionUser = ctx.session.user as { id: string; role?: string };
      const caption = await ctx.prisma.videoCaption.findUnique({
        where: { id: input.captionId },
        select: {
          assetKey: true,
          video: { select: { ownerId: true } },
        },
      });
      if (!caption) throw new TRPCError({ code: "NOT_FOUND" });
      if (
        caption.video.ownerId !== sessionUser.id &&
        sessionUser.role !== "ADMIN"
      ) {
        throw new TRPCError({ code: "FORBIDDEN" });
      }
      await ctx.prisma.videoCaption.delete({ where: { id: input.captionId } });
      removeObject(config.buckets.assets, caption.assetKey).catch(
        () => undefined,
      );
      return { ok: true };
    }),

  setDefault: protectedProcedure
    .input(z.object({ captionId: z.string().min(1) }))
    .mutation(async ({ ctx, input }) => {
      const sessionUser = ctx.session.user as { id: string; role?: string };
      const caption = await ctx.prisma.videoCaption.findUnique({
        where: { id: input.captionId },
        select: {
          videoId: true,
          video: { select: { ownerId: true } },
        },
      });
      if (!caption) throw new TRPCError({ code: "NOT_FOUND" });
      if (
        caption.video.ownerId !== sessionUser.id &&
        sessionUser.role !== "ADMIN"
      ) {
        throw new TRPCError({ code: "FORBIDDEN" });
      }
      await ctx.prisma.$transaction([
        ctx.prisma.videoCaption.updateMany({
          where: { videoId: caption.videoId },
          data: { isDefault: false },
        }),
        ctx.prisma.videoCaption.update({
          where: { id: input.captionId },
          data: { isDefault: true },
        }),
      ]);
      return { ok: true };
    }),
});

const videoSlug = customAlphabet(
  "23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz",
  11,
);

export const videoRouter = router({
  // Öffentliche Startseiten-Liste. Sichtbarkeit: ausschließlich PUBLIC + LIVE.
  // UNLISTED/PRIVATE kommen hier nicht rein — die sind nur per Direkt-Slug
  // abrufbar (siehe `get`).
  list: publicProcedure
    .input(
      z
        .object({
          limit: z.number().int().min(1).max(50).default(20),
          // "LONG" = Startseiten-Feed (default). "SHORT" = Shorts-Feed.
          // "ALL" ignoriert Format — für Admin-Views.
          format: z.enum(["ALL", "LONG", "SHORT"]).default("LONG"),
          // Cursor-Pagination: ID des letzten geladenen Videos.
          cursor: z.string().optional(),
        })
        .optional(),
    )
    .query(async ({ ctx, input }) => {
      const limit = input?.limit ?? 20;
      const format = input?.format ?? "LONG";
      const cursor = input?.cursor;
      return ctx.prisma.video.findMany({
        where: {
          visibility: "PUBLIC",
          status: "LIVE",
          ...(format !== "ALL" ? { format } : {}),
        },
        orderBy: { publishedAt: "desc" },
        take: limit,
        ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}),
        select: {
          id: true,
          slug: true,
          title: true,
          description: true,
          thumbnailKey: true,
          durationSec: true,
          viewCount: true,
          publishedAt: true,
          format: true,
          channel: {
            select: {
              id: true,
              slug: true,
              displayName: true,
              ownerId: true,
              accentColor: true,
              avatarUrl: true,
            },
          },
          captions: {
            select: {
              id: true,
              language: true,
              label: true,
              assetKey: true,
              isDefault: true,
              isAutoGenerated: true,
            },
            orderBy: [{ isDefault: "desc" }, { language: "asc" }],
          },
          _count: { select: { comments: true } },
        },
      });
    }),

  // Einzel-Get per Slug ODER ID. canViewVideo enforced die Sichtbarkeit
  // (PRIVATE nur für Owner/ADMIN, LOGGED_IN nur mit Session).
  get: publicProcedure
    .input(z.object({ idOrSlug: z.string().min(1) }))
    .query(async ({ ctx, input }) => {
      const video = await ctx.prisma.video.findFirst({
        where: {
          OR: [{ id: input.idOrSlug }, { slug: input.idOrSlug }],
        },
        select: {
          id: true,
          slug: true,
          title: true,
          description: true,
          tags: true,
          chapters: true,
          commentsEnabled: true,
          status: true,
          visibility: true,
          ownerId: true,
          thumbnailKey: true,
          durationSec: true,
          width: true,
          height: true,
          viewCount: true,
          createdAt: true,
          publishedAt: true,
          failureReason: true,
          channel: {
            select: {
              id: true,
              slug: true,
              displayName: true,
              ownerId: true,
            },
          },
          category: {
            select: { slug: true, name: true, icon: true },
          },
        },
      });
      if (!video) throw new TRPCError({ code: "NOT_FOUND" });

      const sessionUser = ctx.session?.user as
        | { id: string; role?: string }
        | undefined;
      const viewer = sessionUser
        ? { id: sessionUser.id, role: (sessionUser.role ?? "VIEWER") as Role }
        : null;

      const allowed = canViewVideo(
        { visibility: video.visibility as Visibility, ownerId: video.ownerId },
        viewer,
      );
      if (!allowed) throw new TRPCError({ code: "FORBIDDEN" });

      return video;
    }),

  // Public view-increment — idempotent pro Session ist komplexer als wir
  // jetzt brauchen. Rate-Limits (IP-bucket, max. 1/Session) kommen später.
  recordView: publicProcedure
    .input(z.object({ id: z.string().min(1) }))
    .mutation(async ({ ctx, input }) => {
      await ctx.prisma.video
        .update({
          where: { id: input.id },
          data: { viewCount: { increment: 1 } },
          select: { id: true },
        })
        .catch(() => null);
      return { ok: true as const };
    }),

  // Owner-only Mutation: Sichtbarkeit ändern (Studio).
  setVisibility: protectedProcedure
    .input(
      z.object({
        id: z.string().min(1),
        visibility: z.enum(VISIBILITIES),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      const video = await ctx.prisma.video.findUnique({
        where: { id: input.id },
        select: { ownerId: true },
      });
      if (!video) throw new TRPCError({ code: "NOT_FOUND" });
      const sessionUser = ctx.session.user as { id: string; role?: string };
      if (
        video.ownerId !== sessionUser.id &&
        sessionUser.role !== "ADMIN"
      ) {
        throw new TRPCError({ code: "FORBIDDEN" });
      }
      return ctx.prisma.video.update({
        where: { id: input.id },
        data: { visibility: input.visibility },
        select: { id: true, visibility: true },
      });
    }),

  // Studio — alle Metadaten in einem Request. Owner oder Admin.
  update: protectedProcedure
    .input(
      z.object({
        id: z.string().min(1),
        title: z.string().trim().min(1).max(200).optional(),
        description: z.string().max(10_000).nullable().optional(),
        tags: z.array(z.string().trim().min(1).max(40)).max(20).optional(),
        visibility: z.enum(VISIBILITIES).optional(),
        commentsEnabled: z.boolean().optional(),
        categoryId: z.string().min(1).nullable().optional(),
        thumbnailKey: z.string().min(1).optional(),
        format: z.enum(["LONG", "SHORT"]).optional(),
        chapters: z
          .array(
            z.object({
              timeSec: z.number().int().min(0),
              title: z.string().trim().min(1).max(120),
            }),
          )
          .max(50)
          .optional(),
        // ISO string | null. `null` clears den Zeitplan.
        scheduledPublishAt: z
          .union([z.string().datetime(), z.null()])
          .optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      const video = await ctx.prisma.video.findUnique({
        where: { id: input.id },
        select: { ownerId: true, thumbnailCandidates: true },
      });
      if (!video) throw new TRPCError({ code: "NOT_FOUND" });
      const sessionUser = ctx.session.user as { id: string; role?: string };
      if (
        video.ownerId !== sessionUser.id &&
        sessionUser.role !== "ADMIN"
      ) {
        throw new TRPCError({ code: "FORBIDDEN" });
      }

      // Prevent the creator from pointing thumbnailKey at anything that isn't
      // a candidate we generated (stops arbitrary-key injection).
      if (
        input.thumbnailKey &&
        !video.thumbnailCandidates.includes(input.thumbnailKey)
      ) {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: "thumbnailKey muss aus thumbnailCandidates stammen.",
        });
      }

      const data: Record<string, unknown> = {};
      if (input.title !== undefined) data.title = input.title;
      if (input.description !== undefined) data.description = input.description;
      if (input.tags !== undefined) {
        data.tags = input.tags.map((t) => t.toLowerCase());
      }
      if (input.visibility !== undefined) data.visibility = input.visibility;
      if (input.commentsEnabled !== undefined) {
        data.commentsEnabled = input.commentsEnabled;
      }
      if (input.thumbnailKey !== undefined) data.thumbnailKey = input.thumbnailKey;
      if (input.categoryId !== undefined) data.categoryId = input.categoryId;
      if (input.format !== undefined) data.format = input.format;
      if (input.chapters !== undefined) {
        // Normalize: sort by time ascending.
        const sorted = [...input.chapters].sort((a, b) => a.timeSec - b.timeSec);
        data.chapters = sorted;
      }
      if (input.scheduledPublishAt !== undefined) {
        data.scheduledPublishAt = input.scheduledPublishAt
          ? new Date(input.scheduledPublishAt)
          : null;
      }

      return ctx.prisma.video.update({
        where: { id: input.id },
        data: data as never,
        select: { id: true },
      });
    }),

  // Full editor load — owner/admin only, includes description, tags,
  // chapters, candidate thumbnails. Separate from `get` so the public
  // `get` stays lean.
  getForEdit: protectedProcedure
    .input(z.object({ id: z.string().min(1) }))
    .query(async ({ ctx, input }) => {
      const video = await ctx.prisma.video.findUnique({
        where: { id: input.id },
        select: {
          id: true,
          slug: true,
          title: true,
          description: true,
          tags: true,
          chapters: true,
          commentsEnabled: true,
          categoryId: true,
          visibility: true,
          status: true,
          ownerId: true,
          thumbnailKey: true,
          thumbnailCandidates: true,
          durationSec: true,
          width: true,
          height: true,
          failureReason: true,
          format: true,
          createdAt: true,
          publishedAt: true,
          scheduledPublishAt: true,
          channel: { select: { slug: true, displayName: true, avatarUrl: true } },
        },
      });
      if (!video) throw new TRPCError({ code: "NOT_FOUND" });
      const sessionUser = ctx.session.user as { id: string; role?: string };
      if (
        video.ownerId !== sessionUser.id &&
        sessionUser.role !== "ADMIN"
      ) {
        throw new TRPCError({ code: "FORBIDDEN" });
      }
      return video;
    }),

  // External-URL-Import via yt-dlp. Default-Visibility = PRIVATE
  // (Urheberrechts-Safeguard) — User muss manuell auf PUBLIC schalten.
  import: protectedProcedure
    .input(
      z.object({
        url: z.string().url(),
        title: z.string().trim().max(200).optional(),
        format: z.enum(["LONG", "SHORT"]).optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      const channel = await ctx.prisma.channel.findFirst({
        where: { ownerId: ctx.session.user.id },
        orderBy: { createdAt: "asc" },
        select: { id: true },
      });
      if (!channel) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Kein Default-Channel — Sign-up-Hook defekt?",
        });
      }

      const videoId = randomUUID();
      const slug = videoSlug();
      const placeholderTitle =
        input.title?.trim() || `Import läuft — ${new URL(input.url).hostname}`;

      const video = await ctx.prisma.video.create({
        data: {
          id: videoId,
          slug,
          ownerId: ctx.session.user.id,
          channelId: channel.id,
          title: placeholderTitle,
          source: "EXTERNAL",
          sourceUrl: input.url,
          visibility: "PRIVATE",
          status: "PENDING",
          ...(input.format ? { format: input.format } : {}),
        },
        select: { id: true, slug: true, status: true },
      });

      await importQueue.add(
        "import",
        { videoId, url: input.url, formatHint: input.format },
        { jobId: `import-${videoId}` },
      );

      return {
        videoId: video.id,
        slug: video.slug,
        status: video.status,
      };
    }),

  // Owner/Admin kann Videos (inkl. FAILED/PENDING) wegwerfen.
  // MinIO-Keys werden best-effort parallel dazu entfernt — DB-Row ist aber
  // die Source of Truth, deshalb zuerst löschen.
  delete: protectedProcedure
    .input(z.object({ id: z.string().min(1) }))
    .mutation(async ({ ctx, input }) => {
      const video = await ctx.prisma.video.findUnique({
        where: { id: input.id },
        select: { ownerId: true },
      });
      if (!video) throw new TRPCError({ code: "NOT_FOUND" });
      const sessionUser = ctx.session.user as { id: string; role?: string };
      if (
        video.ownerId !== sessionUser.id &&
        sessionUser.role !== "ADMIN"
      ) {
        throw new TRPCError({ code: "FORBIDDEN" });
      }
      await ctx.prisma.video.delete({ where: { id: input.id } });
      // MinIO-Cleanup bleibt best-effort. Orphan-Sweep-Job kommt in v0.2.
      return { ok: true };
    }),

  // Trim: schneidet das Original auf [startSec, endSec] und re-transcoded.
  // Der Job-Handler im Worker überschreibt raw/<id>.mp4 — kein Snapshot.
  trim: protectedProcedure
    .input(
      z.object({
        videoId: z.string().min(1),
        startSec: z.number().min(0),
        endSec: z.number().min(0.1),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      if (input.endSec <= input.startSec) {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: "endSec muss größer als startSec sein.",
        });
      }
      const sessionUser = ctx.session.user as { id: string; role?: string };
      const video = await ctx.prisma.video.findUnique({
        where: { id: input.videoId },
        select: {
          id: true,
          ownerId: true,
          status: true,
          durationSec: true,
        },
      });
      if (!video) throw new TRPCError({ code: "NOT_FOUND" });
      if (
        video.ownerId !== sessionUser.id &&
        sessionUser.role !== "ADMIN"
      ) {
        throw new TRPCError({ code: "FORBIDDEN" });
      }
      if (video.status === "PROCESSING") {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: "Video wird gerade verarbeitet — kurz warten.",
        });
      }
      if (video.durationSec && input.endSec > video.durationSec + 1) {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: "endSec liegt hinter der Video-Dauer.",
        });
      }

      await ctx.prisma.video.update({
        where: { id: video.id },
        data: { status: "PROCESSING" },
      });

      await trimQueue.add(
        "trim",
        {
          videoId: video.id,
          rawKey: `${video.id}.mp4`,
          startSec: input.startSec,
          endSec: input.endSec,
        },
        { jobId: `trim-${video.id}-${Date.now()}` },
      );
      return { ok: true };
    }),

  captions: captionsRouter,

  // Eigene Uploads — für /studio-View.
  mine: protectedProcedure
    .input(
      z
        .object({ limit: z.number().int().min(1).max(100).default(50) })
        .optional(),
    )
    .query(({ ctx, input }) =>
      ctx.prisma.video.findMany({
        where: { ownerId: ctx.session.user.id },
        orderBy: { createdAt: "desc" },
        take: input?.limit ?? 50,
        select: {
          id: true,
          slug: true,
          title: true,
          status: true,
          visibility: true,
          thumbnailKey: true,
          durationSec: true,
          createdAt: true,
          publishedAt: true,
          failureReason: true,
          format: true,
          viewCount: true,
        },
      }),
    ),
});
