-- Add isAutoGenerated flag to VideoCaption.
-- Additive, non-breaking: all existing rows get the default false.

ALTER TABLE "VideoCaption"
  ADD COLUMN IF NOT EXISTS "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;
