"use client";

import { Suspense, useEffect, useRef, useState, useCallback } from "react";
import { useSearchParams } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { trpc } from "@/lib/trpc";
import { useSession } from "@/lib/auth-client";
import { videoHlsUrl, thumbnailUrl, captionUrl } from "@/lib/storage-urls";
import { Icon } from "@/components/icon";
import { SubscribeButton } from "@/components/subscribe-button";
import { ShareButton } from "@/components/video-actions";
import Hls from "hls.js";

// Typ für ein einzelnes Short-Video
interface ShortCaption {
  id: string;
  language: string;
  label: string | null;
  assetKey: string;
  isDefault: boolean;
  isAutoGenerated: boolean;
}

interface ShortVideo {
  id: string;
  slug: string;
  title: string;
  description: string | null;
  thumbnailKey: string | null;
  durationSec: number | null;
  viewCount: number;
  publishedAt: string | Date | null;
  format: "LONG" | "SHORT";
  captions?: ShortCaption[];
  _count?: { comments: number };
  channel: {
    id: string;
    slug: string;
    displayName: string;
    ownerId: string;
    accentColor: string | null;
    avatarUrl: string | null;
  };
}

// ─── Einzelner Short-Player-Slide ────────────────────────────────────────────

function ShortSlide({
  video,
  active,
  preload,
  muted,
  volume,
  onMuteToggle,
  onVolumeChange,
}: {
  video: ShortVideo;
  active: boolean;
  preload: boolean;
  muted: boolean;
  volume: number;
  onMuteToggle: () => void;
  onVolumeChange: (v: number) => void;
}) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const frameRef = useRef<HTMLDivElement>(null);
  const hlsRef = useRef<Hls | null>(null);
  const hideTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const sliderTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const [loaded, setLoaded] = useState(false);
  const [paused, setPaused] = useState(false);
  const [controlsVisible, setControlsVisible] = useState(true);
  const [ccLanguage, setCcLanguage] = useState<string | null>(null);
  const [dotsOpen, setDotsOpen] = useState(false);
  const [descriptionOpen, setDescriptionOpen] = useState(false);
  const [playlistPickerOpen, setPlaylistPickerOpen] = useState(false);
  const [reportOpen, setReportOpen] = useState(false);
  const [commentsOpen, setCommentsOpen] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [sliderOpen, setSliderOpen] = useState(false);

  const src = videoHlsUrl(video.id);
  const captions = video.captions ?? [];
  const hasCaptions = captions.length > 0;

  const { data: session } = useSession();

  // ─── tRPC queries / mutations ────────────────────────────────────────
  const likeCount = trpc.reaction.countForVideo.useQuery(
    { videoId: video.id },
    { staleTime: 60_000 },
  );
  const myReaction = trpc.reaction.mine.useQuery(
    { videoId: video.id },
    { staleTime: 60_000 },
  );
  const toggleLike = trpc.reaction.toggle.useMutation({
    onSuccess: () => {
      likeCount.refetch();
      myReaction.refetch();
    },
  });

  // ─── Volume + Mute spiegeln ──────────────────────────────────────────
  useEffect(() => {
    const el = videoRef.current;
    if (!el) return;
    el.volume = volume;
    el.muted = muted;
  }, [volume, muted, loaded]);

  // ─── HLS-Setup ───────────────────────────────────────────────────────
  useEffect(() => {
    if (!preload && !active) return;
    const el = videoRef.current;
    if (!el) return;

    if (el.canPlayType("application/vnd.apple.mpegurl")) {
      el.src = src;
      return;
    }

    if (Hls.isSupported()) {
      const hls = new Hls({ enableWorker: true, lowLatencyMode: false });
      hls.loadSource(src);
      hls.attachMedia(el);
      hlsRef.current = hls;
      return () => {
        hls.destroy();
        hlsRef.current = null;
      };
    }

    el.src = src;
  }, [src, preload, active]);

  // ─── Autoplay / Pause je nach aktivem Slide ──────────────────────────
  // Beim Slide-Wechsel reset paused-State (User-Pause war für vorherigen Slide).
  useEffect(() => {
    const el = videoRef.current;
    if (!el) return;
    if (active) {
      setPaused(false);
      el.currentTime = 0;
      el.play().catch(() => null);
    } else {
      el.pause();
    }
  }, [active]);

  // ─── Captions-Track-Mode steuern ─────────────────────────────────────
  // <track> mit `default` reicht nicht — wir müssen track.mode explizit
  // togglen, damit der Wechsel ohne Reload funktioniert.
  useEffect(() => {
    const el = videoRef.current;
    if (!el) return;
    const tracks = el.textTracks;
    for (let i = 0; i < tracks.length; i++) {
      const t = tracks[i];
      if (t) t.mode = t.language === ccLanguage ? "showing" : "disabled";
    }
  }, [ccLanguage, loaded]);

  // ─── Fullscreen-Listener ─────────────────────────────────────────────
  useEffect(() => {
    const onChange = () => setIsFullscreen(!!document.fullscreenElement);
    document.addEventListener("fullscreenchange", onChange);
    return () => document.removeEventListener("fullscreenchange", onChange);
  }, []);

  // ─── Auto-Hide für Player-Controls ───────────────────────────────────
  function resetHideTimer() {
    setControlsVisible(true);
    if (hideTimerRef.current) clearTimeout(hideTimerRef.current);
    // Nicht ausblenden solange pausiert oder ein Sub-Menü offen ist.
    if (paused || dotsOpen || descriptionOpen || playlistPickerOpen || reportOpen || commentsOpen) return;
    hideTimerRef.current = setTimeout(() => setControlsVisible(false), 2500);
  }

  function showSliderTransiently() {
    setSliderOpen(true);
    if (sliderTimerRef.current) clearTimeout(sliderTimerRef.current);
    sliderTimerRef.current = setTimeout(() => setSliderOpen(false), 2500);
  }

  // ─── Action-Handler ──────────────────────────────────────────────────
  function togglePause() {
    const el = videoRef.current;
    if (!el) return;
    if (el.paused) {
      el.play().catch(() => null);
      setPaused(false);
    } else {
      el.pause();
      setPaused(true);
    }
  }

  function handleVideoClick() {
    // Nur togglen, wenn der Klick wirklich aufs Video ging — nicht auf Overlay.
    togglePause();
    resetHideTimer();
  }

  function toggleCaptions() {
    if (!hasCaptions) return;
    if (ccLanguage) {
      setCcLanguage(null);
    } else {
      const def = captions.find((c) => c.isDefault) ?? captions[0];
      if (def) setCcLanguage(def.language);
    }
  }

  async function toggleFullscreen() {
    const el = frameRef.current;
    if (!el) return;
    if (document.fullscreenElement) {
      await document.exitFullscreen().catch(() => null);
    } else {
      await el.requestFullscreen().catch(() => null);
    }
  }

  // ─── Render ──────────────────────────────────────────────────────────
  return (
    <div className="relative flex h-[calc(100dvh-68px)] w-full snap-start snap-always items-center justify-center bg-background p-3 sm:p-4 md:bg-black md:p-4">
      {/* Poster-Blur-Background — full-bleed dahinter, nur Desktop sichtbar */}
      {video.thumbnailKey && !loaded && (
        // eslint-disable-next-line react/forbid-dom-props
        <div
          className="absolute inset-0 hidden scale-110 bg-cover bg-center opacity-30 blur-xl md:block"
          style={{ backgroundImage: `url(${thumbnailUrl(video.thumbnailKey)})` }}
        />
      )}

      {/* Layout-Wrapper:
          Mobile = Video 9:16 zentriert mit Padding rundum (wie YouTube)
          Desktop = 9:16 zentriert + Action-Bar als eigene Spalte daneben */}
      <div className="relative z-10 flex h-full w-full items-center justify-center md:gap-3">
        {/* Video-Frame — IMMER 9:16, mit border-radius, eingerahmt */}
        <div
          ref={frameRef}
          className="group/frame relative aspect-[9/16] h-full max-h-full w-auto max-w-full overflow-hidden rounded-xl bg-black shadow-2xl md:max-w-[min(420px,calc((100dvh-100px)*9/16))]"
          onMouseMove={resetHideTimer}
          onMouseLeave={() => {
            if (!paused && !dotsOpen && !descriptionOpen && !playlistPickerOpen && !reportOpen && !commentsOpen) {
              setControlsVisible(false);
            }
          }}
          onTouchStart={resetHideTimer}
        >
          {/* Video — Click-to-Pause */}
          <video
            ref={videoRef}
            muted={muted}
            loop
            playsInline
            poster={video.thumbnailKey ? thumbnailUrl(video.thumbnailKey) : undefined}
            className="h-full w-full object-cover md:object-contain"
            onLoadedData={() => setLoaded(true)}
            onClick={handleVideoClick}
            crossOrigin={hasCaptions ? "anonymous" : undefined}
          >
            {captions.map((c) => (
              <track
                key={c.id}
                kind="subtitles"
                src={captionUrl(c.assetKey)}
                srcLang={c.language}
                label={c.label ?? c.language.toUpperCase()}
              />
            ))}
          </video>

          {/* Mittiger Pause/Play-Indicator beim Tap (kurz sichtbar) */}
          {paused && (
            <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
              <div className="grid h-20 w-20 place-items-center rounded-full bg-black/60 backdrop-blur-sm">
                <Icon name="play" size={40} className="ml-1 text-white" />
              </div>
            </div>
          )}

          {/* ─── TopControls (overlay) ──────────────────────────────── */}
          <div
            className={
              "pointer-events-none absolute inset-x-0 top-0 z-20 flex items-start justify-between p-3 transition-opacity " +
              (controlsVisible || paused ? "opacity-100" : "opacity-0")
            }
          >
            {/* Top-Left: Pause + Volume */}
            <div className="pointer-events-auto flex items-center gap-2">
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  togglePause();
                }}
                className="grid h-10 w-10 place-items-center rounded-full bg-black/50 text-white backdrop-blur-sm transition active:scale-90"
                aria-label={paused ? "Abspielen" : "Pausieren"}
              >
                <Icon name={paused ? "play" : "pause"} size={18} />
              </button>

              {/* Volume — Desktop: hover-expand, Mobile: tap öffnet Pop-Up */}
              <div
                className="relative flex items-center"
                onMouseEnter={() => setSliderOpen(true)}
                onMouseLeave={() => setSliderOpen(false)}
              >
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    // Mobile-Tap: Erster Tap öffnet Slider, zweiter Tap toggled mute.
                    // Desktop: Klick toggled immer mute (Slider ist über Hover schon offen).
                    if (!sliderOpen) {
                      showSliderTransiently();
                    } else {
                      onMuteToggle();
                      showSliderTransiently();
                    }
                  }}
                  className="grid h-10 w-10 place-items-center rounded-full bg-black/50 text-white backdrop-blur-sm transition active:scale-90"
                  aria-label={muted ? "Ton einschalten" : "Stummschalten"}
                >
                  <Icon
                    name={muted || volume === 0 ? "volume-x" : "volume-2"}
                    size={18}
                  />
                </button>
                {/* Slider-Container — Desktop: rechts vom Button (inline-expand),
                    Mobile: absolut darunter als Pop-Up. */}
                <div
                  className={
                    "ml-1 hidden overflow-hidden transition-[width] duration-200 md:block " +
                    (sliderOpen ? "md:w-28" : "md:w-0")
                  }
                  onClick={(e) => e.stopPropagation()}
                >
                  <div className="flex h-10 items-center rounded-full bg-black/50 px-3 backdrop-blur-sm">
                    <input
                      type="range"
                      min={0}
                      max={1}
                      step={0.01}
                      value={muted ? 0 : volume}
                      onChange={(e) => onVolumeChange(parseFloat(e.target.value))}
                      aria-label="Lautstärke"
                      className="h-1 w-full cursor-pointer appearance-none rounded-full bg-white/30 accent-brand [&::-webkit-slider-thumb]:h-3 [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-white"
                    />
                  </div>
                </div>
                {/* Mobile-Pop-Up: absolut darunter, breiter Slider */}
                <div
                  className={
                    "absolute left-0 top-12 z-30 transition-opacity md:hidden " +
                    (sliderOpen
                      ? "pointer-events-auto opacity-100"
                      : "pointer-events-none opacity-0")
                  }
                  onClick={(e) => e.stopPropagation()}
                  onTouchStart={(e) => e.stopPropagation()}
                >
                  <div className="flex h-10 w-44 items-center rounded-full bg-black/70 px-4 shadow-lg backdrop-blur-sm">
                    <input
                      type="range"
                      min={0}
                      max={1}
                      step={0.01}
                      value={muted ? 0 : volume}
                      onChange={(e) => {
                        onVolumeChange(parseFloat(e.target.value));
                        showSliderTransiently();
                      }}
                      aria-label="Lautstärke"
                      className="h-1 w-full cursor-pointer appearance-none rounded-full bg-white/30 accent-brand [&::-webkit-slider-thumb]:h-4 [&::-webkit-slider-thumb]:w-4 [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-white"
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* Top-Right: CC + 3-Dot + Fullscreen */}
            <div className="pointer-events-auto flex items-center gap-2">
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  toggleCaptions();
                }}
                disabled={!hasCaptions}
                aria-label={
                  !hasCaptions
                    ? "Keine Untertitel verfügbar"
                    : ccLanguage
                      ? "Untertitel ausschalten"
                      : "Untertitel einschalten"
                }
                aria-pressed={ccLanguage ? "true" : "false"}
                className={
                  "grid h-10 w-10 place-items-center rounded-full text-white backdrop-blur-sm transition active:scale-90 " +
                  (hasCaptions
                    ? ccLanguage
                      ? "bg-brand text-neutral-900"
                      : "bg-black/50"
                    : "cursor-not-allowed bg-black/30 opacity-40")
                }
              >
                <span className="text-[11px] font-bold tracking-tight">CC</span>
              </button>

              <div className="relative">
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    setDotsOpen((o) => !o);
                  }}
                  className="grid h-10 w-10 place-items-center rounded-full bg-black/50 text-white backdrop-blur-sm transition active:scale-90"
                  aria-label="Mehr Optionen"
                  aria-haspopup="menu"
                  aria-expanded={dotsOpen ? "true" : "false"}
                >
                  <Icon name="more-vertical" size={18} />
                </button>
                {dotsOpen && (
                  <DotsMenu
                    onClose={() => setDotsOpen(false)}
                    onShowDescription={() => {
                      setDotsOpen(false);
                      setDescriptionOpen(true);
                    }}
                    onAddToPlaylist={() => {
                      setDotsOpen(false);
                      setPlaylistPickerOpen(true);
                    }}
                    onReport={() => {
                      setDotsOpen(false);
                      setReportOpen(true);
                    }}
                  />
                )}
              </div>

              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  toggleFullscreen();
                }}
                className="hidden h-10 w-10 place-items-center rounded-full bg-black/50 text-white backdrop-blur-sm transition active:scale-90 md:grid"
                aria-label={isFullscreen ? "Vollbild verlassen" : "Vollbild"}
              >
                <Icon name={isFullscreen ? "minimize" : "maximize"} size={18} />
              </button>
            </div>
          </div>

          {/* ─── Bottom-Left: Channel + Titel + Subscribe ──────────── */}
          <div
            className="absolute bottom-0 left-0 right-0 z-10 bg-gradient-to-t from-black/85 via-black/40 to-transparent px-4 pb-4 pr-20 pt-12 md:pr-4"
            onClick={(e) => e.stopPropagation()}
          >
            <Link
              href={`/c/${video.channel.slug}`}
              className="block text-[13px] font-semibold text-white/85 hover:text-brand"
            >
              @{video.channel.slug}
            </Link>
            <Link href={`/watch/${video.slug}`}>
              <h2 className="mt-1 line-clamp-2 text-sm font-bold leading-snug text-white">
                {video.title}
              </h2>
            </Link>
            <div className="mt-2.5">
              <SubscribeButton
                channelId={video.channel.id}
                channelOwnerId={video.channel.ownerId}
                accentColor={video.channel.accentColor ?? undefined}
                size="sm"
              />
            </div>
          </div>

          {/* ─── Mobile Action-Bar als Overlay rechts INNEN ────────── */}
          <ActionBar
            layout="overlay"
            video={video}
            session={session}
            likeCount={likeCount.data ?? 0}
            liked={!!myReaction.data?.liked}
            onLike={() => session && toggleLike.mutate({ videoId: video.id })}
            onCommentsClick={() => setCommentsOpen(true)}
            onClickStop={(e) => e.stopPropagation()}
          />

          {/* ─── Description Bottom-Sheet ──────────────────────────── */}
          {descriptionOpen && (
            <div
              className="absolute inset-0 z-30 flex items-end bg-black/40 backdrop-blur-sm"
              onClick={(e) => {
                e.stopPropagation();
                setDescriptionOpen(false);
              }}
            >
              <div
                className="max-h-[70%] w-full overflow-y-auto rounded-t-xl bg-surface p-4"
                onClick={(e) => e.stopPropagation()}
              >
                <div className="mb-3 flex items-center justify-between">
                  <h3 className="text-base font-bold text-foreground">
                    {video.title}
                  </h3>
                  <button
                    type="button"
                    onClick={() => setDescriptionOpen(false)}
                    aria-label="Schließen"
                    className="rounded-md p-1 text-muted hover:bg-surface-raised hover:text-foreground"
                  >
                    <Icon name="x" size={18} />
                  </button>
                </div>
                <div className="mb-3 text-[11px] text-dim">
                  @{video.channel.slug} · {video.viewCount} Aufrufe
                </div>
                <p className="whitespace-pre-line text-sm text-foreground/90">
                  {video.description?.trim() || "Keine Beschreibung vorhanden."}
                </p>
              </div>
            </div>
          )}

          {/* ─── Playlist-Picker ───────────────────────────────────── */}
          {playlistPickerOpen && (
            <PlaylistPicker
              videoId={video.id}
              hasSession={!!session}
              onClose={() => setPlaylistPickerOpen(false)}
            />
          )}

          {/* ─── Report-Dialog ─────────────────────────────────────── */}
          {reportOpen && (
            <ReportDialog
              videoId={video.id}
              hasSession={!!session}
              onClose={() => setReportOpen(false)}
            />
          )}

          {/* ─── Comments-Sheet ────────────────────────────────────── */}
          {commentsOpen && (
            <CommentsSheet
              videoId={video.id}
              hasSession={!!session}
              onClose={() => setCommentsOpen(false)}
            />
          )}
        </div>

        {/* ─── Desktop-Action-Bar als eigene Spalte rechts AUSSEN ── */}
        <ActionBar
          layout="column"
          video={video}
          session={session}
          likeCount={likeCount.data ?? 0}
          liked={!!myReaction.data?.liked}
          onLike={() => session && toggleLike.mutate({ videoId: video.id })}
          onCommentsClick={() => setCommentsOpen(true)}
        />
      </div>
    </div>
  );
}

// ─── DotsMenu ─────────────────────────────────────────────────────────────────

function DotsMenu({
  onClose,
  onShowDescription,
  onAddToPlaylist,
  onReport,
}: {
  onClose: () => void;
  onShowDescription: () => void;
  onAddToPlaylist: () => void;
  onReport: () => void;
}) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const onClick = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) onClose();
    };
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && onClose();
    window.addEventListener("mousedown", onClick);
    window.addEventListener("keydown", onKey);
    return () => {
      window.removeEventListener("mousedown", onClick);
      window.removeEventListener("keydown", onKey);
    };
  }, [onClose]);

  return (
    <div
      ref={ref}
      role="menu"
      className="absolute right-0 top-full z-30 mt-2 w-56 overflow-hidden rounded-lg border border-border bg-surface shadow-[var(--shadow-card)]"
      onClick={(e) => e.stopPropagation()}
    >
      <DotsItem icon="info" label="Beschreibung" onClick={onShowDescription} />
      <DotsItem
        icon="bookmark-plus"
        label="Zur Playlist hinzufügen"
        onClick={onAddToPlaylist}
      />
      <DotsItem icon="flag" label="Melden" onClick={onReport} />
    </div>
  );
}

function DotsItem({
  icon,
  label,
  onClick,
}: {
  icon: "info" | "bookmark-plus" | "flag";
  label: string;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="flex w-full items-center gap-3 border-b border-border px-3 py-2.5 text-left text-sm text-foreground transition last:border-b-0 hover:bg-surface-raised"
    >
      <span className="text-brand">
        <Icon name={icon} size={16} />
      </span>
      {label}
    </button>
  );
}

// ─── ActionBar (Like / Comments / Share / Avatar) ─────────────────────────────

interface ActionBarProps {
  video: ShortVideo;
  session: ReturnType<typeof useSession>["data"];
  likeCount: number;
  liked: boolean;
  layout: "overlay" | "column";
  onLike: () => void;
  onCommentsClick: () => void;
  onClickStop?: (e: React.MouseEvent) => void;
}

function ActionBar({
  video,
  session,
  likeCount,
  liked,
  layout,
  onLike,
  onCommentsClick,
  onClickStop,
}: ActionBarProps) {
  const positionCls =
    layout === "overlay"
      ? "absolute right-2 bottom-32 z-10 flex flex-col items-center gap-4 md:hidden"
      : "hidden shrink-0 flex-col items-center gap-4 self-end pb-6 md:flex";
  return (
    <div className={positionCls} onClick={onClickStop}>
      {/* Avatar */}
      <Link
        href={`/c/${video.channel.slug}`}
        aria-label={`Kanal ${video.channel.displayName}`}
        onClick={onClickStop}
      >
        {video.channel.avatarUrl ? (
          <Image
            src={video.channel.avatarUrl}
            alt={`${video.channel.displayName} Avatar`}
            width={44}
            height={44}
            className="rounded-full border-2 border-white object-cover shadow-lg"
          />
        ) : (
          <div className="grid h-11 w-11 place-items-center rounded-full border-2 border-white bg-gradient-to-br from-teal-400 to-teal-700 text-sm font-bold text-neutral-900 shadow-lg">
            {video.channel.displayName[0]?.toUpperCase() ?? "?"}
          </div>
        )}
      </Link>

      {/* Like */}
      <button
        type="button"
        onClick={(e) => {
          e.stopPropagation();
          onLike();
        }}
        className="flex flex-col items-center gap-1"
        aria-label="Gefällt mir"
      >
        <div className="grid h-12 w-12 place-items-center rounded-full bg-black/50 backdrop-blur-sm transition active:scale-90">
          <Icon
            name={liked ? "heart-filled" : "heart"}
            size={24}
            className={liked ? "text-red-400" : "text-white"}
          />
        </div>
        <span className="text-xs font-semibold text-white drop-shadow">
          {likeCount}
        </span>
      </button>

      {/* Kommentare → öffnet Bottom-Sheet ÜBER dem Short */}
      <button
        type="button"
        onClick={(e) => {
          e.stopPropagation();
          onCommentsClick();
        }}
        className="flex flex-col items-center gap-1"
        aria-label="Kommentare ansehen"
      >
        <div className="grid h-12 w-12 place-items-center rounded-full bg-black/50 backdrop-blur-sm transition active:scale-90">
          <Icon name="message" size={24} className="text-white" />
        </div>
        <span className="text-xs font-semibold text-white drop-shadow">
          {video._count?.comments ?? 0}
        </span>
      </button>

      {/* Share */}
      <div onClick={onClickStop}>
        <ShareButton
          slug={video.slug}
          title={video.title}
          thumbnailKey={video.thumbnailKey}
          channelName={video.channel.displayName}
          channelSlug={video.channel.slug}
          variant="compact"
        />
      </div>

      {/* Mute-Hint nur wenn keine Session aktiv (sonst Pflicht aus YT-Sicht: nichts) */}
      {!session && (
        <Link
          href="/login"
          className="flex flex-col items-center gap-1"
          aria-label="Anmelden"
          onClick={onClickStop}
        >
          <div className="grid h-12 w-12 place-items-center rounded-full bg-black/50 backdrop-blur-sm">
            <Icon name="user" size={22} className="text-white" />
          </div>
          <span className="text-[10px] font-semibold text-white drop-shadow">
            Login
          </span>
        </Link>
      )}
    </div>
  );
}

// ─── PlaylistPicker ───────────────────────────────────────────────────────────

function PlaylistPicker({
  videoId,
  hasSession,
  onClose,
}: {
  videoId: string;
  hasSession: boolean;
  onClose: () => void;
}) {
  const playlists = trpc.playlist.mine.useQuery(undefined, {
    enabled: hasSession,
  });
  const addItem = trpc.playlist.addItem.useMutation();
  const [doneId, setDoneId] = useState<string | null>(null);
  const [errorId, setErrorId] = useState<string | null>(null);

  return (
    <div
      className="absolute inset-0 z-30 flex items-center justify-center bg-black/60 backdrop-blur-sm"
      onClick={(e) => {
        e.stopPropagation();
        onClose();
      }}
    >
      <div
        className="max-h-[80%] w-[90%] max-w-sm overflow-y-auto rounded-xl bg-surface p-4 shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="mb-3 flex items-center justify-between">
          <h3 className="text-base font-bold text-foreground">
            Zur Playlist hinzufügen
          </h3>
          <button
            type="button"
            onClick={onClose}
            aria-label="Schließen"
            className="rounded-md p-1 text-muted hover:bg-surface-raised hover:text-foreground"
          >
            <Icon name="x" size={18} />
          </button>
        </div>

        {!hasSession ? (
          <div className="text-center">
            <p className="mb-4 text-sm text-foreground/80">
              Melde dich an, um Videos zu Playlists hinzuzufügen.
            </p>
            <Link
              href="/login"
              className="inline-block rounded-md bg-brand px-4 py-2 text-sm font-medium text-neutral-900 hover:bg-brand-hover"
              onClick={onClose}
            >
              Anmelden
            </Link>
          </div>
        ) : playlists.isPending ? (
          <p className="text-sm text-muted">Lädt …</p>
        ) : (playlists.data?.length ?? 0) === 0 ? (
          <div className="text-center">
            <p className="mb-3 text-sm text-foreground/80">
              Du hast noch keine Playlists.
            </p>
            <Link
              href="/library"
              onClick={onClose}
              className="inline-flex items-center gap-1.5 rounded-md bg-brand px-4 py-2 text-sm font-medium text-neutral-900 hover:bg-brand-hover"
            >
              <Icon name="plus" size={14} />
              Neue Playlist
            </Link>
          </div>
        ) : (
          <ul className="flex flex-col gap-1">
            {playlists.data?.map((p) => {
              const done = doneId === p.id;
              const err = errorId === p.id;
              return (
                <li key={p.id}>
                  <button
                    type="button"
                    disabled={done || addItem.isPending}
                    onClick={() => {
                      setErrorId(null);
                      addItem.mutate(
                        { playlistId: p.id, videoId },
                        {
                          onSuccess: () => setDoneId(p.id),
                          onError: () => setErrorId(p.id),
                        },
                      );
                    }}
                    className={
                      "flex w-full items-center justify-between gap-3 rounded-md px-3 py-2.5 text-left text-sm transition " +
                      (done
                        ? "bg-brand/10 text-brand"
                        : err
                          ? "bg-red-500/10 text-red-400"
                          : "text-foreground hover:bg-surface-raised")
                    }
                  >
                    <span className="truncate">{p.title}</span>
                    {done ? (
                      <Icon name="check" size={16} />
                    ) : err ? (
                      <span className="text-[11px]">Fehler</span>
                    ) : (
                      <Icon name="plus" size={14} className="text-dim" />
                    )}
                  </button>
                </li>
              );
            })}
          </ul>
        )}
      </div>
    </div>
  );
}

// ─── ReportDialog ─────────────────────────────────────────────────────────────

const REPORT_REASONS = [
  { value: "spam", label: "Spam" },
  { value: "abuse", label: "Belästigung / Hass" },
  { value: "copyright", label: "Urheberrecht" },
  { value: "nudity", label: "Nacktheit / Sexuell" },
  { value: "violence", label: "Gewalt" },
  { value: "dangerous", label: "Gefährliche Inhalte" },
  { value: "other", label: "Sonstiges" },
] as const;

type ReportReason = (typeof REPORT_REASONS)[number]["value"];

function ReportDialog({
  videoId,
  hasSession,
  onClose,
}: {
  videoId: string;
  hasSession: boolean;
  onClose: () => void;
}) {
  const [reason, setReason] = useState<ReportReason>("spam");
  const [note, setNote] = useState("");
  const [done, setDone] = useState(false);
  const submit = trpc.report.create.useMutation({
    onSuccess: () => setDone(true),
  });

  return (
    <div
      className="absolute inset-0 z-30 flex items-center justify-center bg-black/60 backdrop-blur-sm"
      onClick={(e) => {
        e.stopPropagation();
        onClose();
      }}
    >
      <div
        className="w-[90%] max-w-sm rounded-xl bg-surface p-4 shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="mb-3 flex items-center justify-between">
          <h3 className="text-base font-bold text-foreground">Video melden</h3>
          <button
            type="button"
            onClick={onClose}
            aria-label="Schließen"
            className="rounded-md p-1 text-muted hover:bg-surface-raised hover:text-foreground"
          >
            <Icon name="x" size={18} />
          </button>
        </div>

        {!hasSession ? (
          <div className="text-center">
            <p className="mb-4 text-sm text-foreground/80">
              Melde dich an, um Videos zu melden.
            </p>
            <Link
              href="/login"
              className="inline-block rounded-md bg-brand px-4 py-2 text-sm font-medium text-neutral-900 hover:bg-brand-hover"
              onClick={onClose}
            >
              Anmelden
            </Link>
          </div>
        ) : done ? (
          <div className="py-4 text-center">
            <Icon name="check" size={28} className="mx-auto mb-2 text-brand" />
            <p className="text-sm text-foreground">
              Danke. Das Mod-Team prüft deinen Hinweis.
            </p>
            <button
              type="button"
              onClick={onClose}
              className="mt-4 rounded-md border border-border-strong px-4 py-2 text-sm text-muted hover:border-muted hover:text-foreground"
            >
              Schließen
            </button>
          </div>
        ) : (
          <>
            <label className="mb-2 block text-xs font-semibold text-dim">
              Grund
            </label>
            <div className="mb-3 flex flex-wrap gap-1.5">
              {REPORT_REASONS.map((r) => (
                <button
                  key={r.value}
                  type="button"
                  onClick={() => setReason(r.value)}
                  className={
                    "rounded-md border px-2.5 py-1.5 text-[12px] transition " +
                    (reason === r.value
                      ? "border-brand bg-brand/10 text-brand"
                      : "border-border bg-background text-muted hover:bg-surface-raised")
                  }
                >
                  {r.label}
                </button>
              ))}
            </div>
            <textarea
              value={note}
              onChange={(e) => setNote(e.target.value)}
              rows={3}
              maxLength={1000}
              placeholder="Optionale Anmerkung …"
              className="w-full rounded-md border border-border bg-background p-2 text-sm text-foreground outline-none focus:border-brand"
            />
            <div className="mt-3 flex justify-end gap-2">
              <button
                type="button"
                onClick={onClose}
                className="rounded-md border border-border-strong px-3 py-2 text-sm text-muted hover:border-muted hover:text-foreground"
              >
                Abbrechen
              </button>
              <button
                type="button"
                disabled={submit.isPending}
                onClick={() =>
                  submit.mutate({
                    targetType: "VIDEO",
                    videoId,
                    reason,
                    note: note.trim() || null,
                  })
                }
                className="rounded-md bg-brand px-3 py-2 text-sm font-medium text-neutral-900 hover:bg-brand-hover disabled:opacity-50"
              >
                {submit.isPending ? "Sende …" : "Melden"}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// ─── CommentsSheet — Bottom-Sheet mit Comments-Liste + Form ──────────────────

function CommentsSheet({
  videoId,
  hasSession,
  onClose,
}: {
  videoId: string;
  hasSession: boolean;
  onClose: () => void;
}) {
  const [body, setBody] = useState("");
  const utils = trpc.useUtils();
  const list = trpc.comment.list.useQuery({ videoId, limit: 100 });
  const create = trpc.comment.create.useMutation({
    onSuccess: () => {
      setBody("");
      list.refetch();
      utils.video.list.invalidate();
    },
  });

  return (
    <div
      className="absolute inset-0 z-30 flex items-end bg-black/40 backdrop-blur-sm"
      onClick={(e) => {
        e.stopPropagation();
        onClose();
      }}
    >
      <div
        className="flex h-[75%] w-full flex-col overflow-hidden rounded-t-xl bg-surface"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-border px-4 py-3">
          <h3 className="text-base font-bold text-foreground">
            Kommentare{" "}
            <span className="text-sm font-normal text-dim">
              · {list.data?.length ?? 0}
            </span>
          </h3>
          <button
            type="button"
            onClick={onClose}
            aria-label="Schließen"
            className="rounded-md p-1 text-muted hover:bg-surface-raised hover:text-foreground"
          >
            <Icon name="x" size={20} />
          </button>
        </div>

        {/* Liste — flat, top-level zuerst */}
        <div className="flex-1 overflow-y-auto px-4 py-3">
          {list.isPending ? (
            <p className="text-sm text-muted">Lädt …</p>
          ) : (list.data?.length ?? 0) === 0 ? (
            <p className="text-sm text-dim">
              Noch keine Kommentare. Sei der Erste.
            </p>
          ) : (
            <ul className="flex flex-col gap-3">
              {list.data
                ?.filter((c) => !c.parentId)
                .map((c) => (
                  <li key={c.id} className="flex gap-2.5">
                    <div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-gradient-to-br from-teal-400 to-teal-700 text-xs font-bold text-neutral-900">
                      {c.user.displayName[0]?.toUpperCase() ?? "?"}
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-baseline gap-2">
                        <span className="text-[13px] font-semibold text-foreground">
                          @{c.user.handle}
                        </span>
                        {c.pinnedAt && (
                          <span className="rounded bg-brand/15 px-1.5 py-0.5 text-[9px] font-bold uppercase text-brand">
                            Pinned
                          </span>
                        )}
                        {c.heartedByCreator && (
                          <Icon
                            name="heart-filled"
                            size={12}
                            className="text-red-400"
                          />
                        )}
                      </div>
                      <p className="mt-0.5 whitespace-pre-line break-words text-sm text-foreground/90">
                        {c.body}
                      </p>
                    </div>
                  </li>
                ))}
            </ul>
          )}
        </div>

        {/* Form */}
        {hasSession ? (
          <form
            onSubmit={(e) => {
              e.preventDefault();
              if (body.trim().length === 0) return;
              create.mutate({ videoId, body: body.trim() });
            }}
            className="border-t border-border p-3"
          >
            <div className="flex items-center gap-2">
              <input
                type="text"
                value={body}
                onChange={(e) => setBody(e.target.value)}
                placeholder="Schreib einen Kommentar …"
                maxLength={4000}
                className="flex-1 rounded-full border border-border bg-background px-4 py-2 text-sm text-foreground outline-none focus:border-brand"
              />
              <button
                type="submit"
                disabled={create.isPending || body.trim().length === 0}
                className="rounded-full bg-brand px-4 py-2 text-sm font-semibold text-neutral-900 transition hover:bg-brand-hover disabled:opacity-50"
              >
                {create.isPending ? "…" : "Senden"}
              </button>
            </div>
            {create.isError && (
              <p className="mt-2 text-xs text-red-400">
                {create.error.message ?? "Fehler beim Senden."}
              </p>
            )}
          </form>
        ) : (
          <div className="border-t border-border p-4 text-center">
            <Link
              href="/login"
              onClick={onClose}
              className="inline-block rounded-md bg-brand px-4 py-2 text-sm font-medium text-neutral-900 hover:bg-brand-hover"
            >
              Anmelden um zu kommentieren
            </Link>
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Haupt-Feed ──────────────────────────────────────────────────────────────

// Wrapper: useSearchParams braucht eine Suspense-Boundary, sonst kann
// Next.js die Page nicht prerendern. Inner-Komponente liest die Params.
export default function ShortsPage() {
  return (
    <Suspense fallback={<div className="h-[calc(100dvh-68px)] bg-black" />}>
      <ShortsFeed />
    </Suspense>
  );
}

function ShortsFeed() {
  const PRELOAD_AHEAD = 2;
  const searchParams = useSearchParams();
  const startSlug = searchParams.get("v");

  const [fetchCursor, setFetchCursor] = useState<string | undefined>(undefined);
  const [items, setItems] = useState<ShortVideo[]>([]);
  const [activeIdx, setActiveIdx] = useState(0);
  // Volume + Mute global pro Tab — alle Slides nutzen dieselben Werte,
  // damit die User-Einstellung beim Scrollen nicht verloren geht.
  // Default: muted=true (Autoplay-Policy fordert das), Volume=0.7.
  const [volume, setVolume] = useState(0.7);
  const [muted, setMuted] = useState(true);

  // Hydrate aus localStorage beim Mount.
  useEffect(() => {
    const v = parseFloat(localStorage.getItem("play-shorts-volume") ?? "");
    if (!Number.isNaN(v) && v >= 0 && v <= 1) setVolume(v);
    const m = localStorage.getItem("play-shorts-muted");
    if (m === "false") setMuted(false);
  }, []);

  function handleVolumeChange(v: number) {
    setVolume(v);
    localStorage.setItem("play-shorts-volume", String(v));
    // Slider auf >0 hebt Mute auf, Slider auf 0 muted.
    if (v > 0 && muted) {
      setMuted(false);
      localStorage.setItem("play-shorts-muted", "false");
    } else if (v === 0 && !muted) {
      setMuted(true);
      localStorage.setItem("play-shorts-muted", "true");
    }
  }

  function handleMuteToggle() {
    setMuted((m) => {
      const next = !m;
      localStorage.setItem("play-shorts-muted", String(next));
      return next;
    });
  }
  const containerRef = useRef<HTMLDivElement>(null);
  const observerRef = useRef<IntersectionObserver | null>(null);
  const slideRefs = useRef<(HTMLDivElement | null)[]>([]);
  const fetchingMore = useRef(false);
  const initialScrollDone = useRef(false);

  const query = trpc.video.list.useQuery(
    { limit: 10, format: "SHORT" },
    { enabled: true },
  );

  const moreQuery = trpc.video.list.useQuery(
    { limit: 10, format: "SHORT", cursor: fetchCursor },
    { enabled: !!fetchCursor },
  );

  // Erste Batch laden
  useEffect(() => {
    if (query.data && items.length === 0) {
      setItems(query.data as ShortVideo[]);
    }
  }, [query.data]);

  // Deep-Link: ?v=slug → erstmal in der bereits geladenen Liste suchen.
  // Falls dort, scroll initial dorthin. Sonst nachladen, bis er auftaucht
  // (übernimmt der bestehende Infinite-Scroll, weil setFetchCursor läuft).
  useEffect(() => {
    if (!startSlug || initialScrollDone.current || items.length === 0) return;
    const idx = items.findIndex((v) => v.slug === startSlug);
    if (idx >= 0) {
      initialScrollDone.current = true;
      setActiveIdx(idx);
      // Warte einen Tick auf Layout, dann scroll ohne Animation.
      requestAnimationFrame(() => {
        slideRefs.current[idx]?.scrollIntoView({ behavior: "auto" });
      });
    }
  }, [startSlug, items]);

  // Nachgeladene Batch anhängen
  useEffect(() => {
    if (moreQuery.data) {
      setItems((prev) => {
        const existingIds = new Set(prev.map((v) => v.id));
        const fresh = (moreQuery.data as ShortVideo[]).filter(
          (v) => !existingIds.has(v.id),
        );
        return fresh.length > 0 ? [...prev, ...fresh] : prev;
      });
      fetchingMore.current = false;
    }
  }, [moreQuery.data]);

  // Keyboard-Navigation ↑/↓
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "ArrowDown" || e.key === "ArrowRight") {
        e.preventDefault();
        scrollToSlide(activeIdx + 1);
      } else if (e.key === "ArrowUp" || e.key === "ArrowLeft") {
        e.preventDefault();
        scrollToSlide(activeIdx - 1);
      }
    };
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [activeIdx, items.length]);

  const scrollToSlide = useCallback(
    (idx: number) => {
      const clamped = Math.max(0, Math.min(idx, items.length - 1));
      slideRefs.current[clamped]?.scrollIntoView({ behavior: "smooth" });
    },
    [items.length],
  );

  // IntersectionObserver: aktiven Slide tracken + Infinite-Scroll-Trigger
  useEffect(() => {
    observerRef.current?.disconnect();
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            const idx = slideRefs.current.indexOf(
              entry.target as HTMLDivElement,
            );
            if (idx !== -1) {
              setActiveIdx(idx);
              // Lade mehr, wenn 3 vor dem Ende
              if (
                idx >= items.length - 3 &&
                items.length > 0 &&
                !fetchingMore.current
              ) {
                const lastId = items[items.length - 1]?.id;
                if (lastId) {
                  fetchingMore.current = true;
                  setFetchCursor(lastId);
                }
              }
            }
          }
        });
      },
      { threshold: 0.6 },
    );
    slideRefs.current.forEach((el) => el && observer.observe(el));
    observerRef.current = observer;
    return () => observer.disconnect();
  }, [items]);

  // Empty state
  if (query.isPending) {
    return (
      <main className="flex h-[calc(100dvh-68px)] items-center justify-center bg-black text-white">
        <p className="text-muted">Lädt …</p>
      </main>
    );
  }

  if (!query.isPending && items.length === 0) {
    return (
      <main className="flex h-[calc(100dvh-68px)] flex-col items-center justify-center gap-4 bg-black px-6 text-center text-white">
        <Icon name="bolt" size={40} className="text-brand" />
        <h1 className="text-2xl font-extrabold">Noch keine Shorts</h1>
        <p className="text-sm text-white/60">
          Lade ein hochformatiges Video unter 60 s hoch — der Worker
          klassifiziert automatisch.
        </p>
        <Link
          href="/studio/new"
          className="mt-2 rounded-lg bg-brand px-5 py-2.5 text-sm font-semibold text-neutral-900 transition hover:bg-brand/90"
        >
          Short erstellen
        </Link>
      </main>
    );
  }

  return (
    <div
      ref={containerRef}
      className="shorts-feed h-[calc(100dvh-68px)] overflow-y-scroll snap-y snap-mandatory"
    >
      {items.map((video, idx) => (
        <div
          key={video.id}
          ref={(el) => {
            slideRefs.current[idx] = el;
          }}
        >
          <ShortSlide
            video={video}
            active={activeIdx === idx}
            preload={idx > activeIdx && idx <= activeIdx + PRELOAD_AHEAD}
            muted={muted}
            volume={volume}
            onMuteToggle={handleMuteToggle}
            onVolumeChange={handleVolumeChange}
          />
        </div>
      ))}

      {/* Keyboard-Hint (nur beim ersten Video sichtbar) */}
      {activeIdx === 0 && items.length > 1 && (
        <div className="pointer-events-none fixed bottom-6 left-1/2 z-30 -translate-x-1/2">
          <div className="flex animate-bounce flex-col items-center gap-1 text-white/60">
            <Icon name="chevron-down" size={20} />
            <span className="text-[11px]">Scrollen oder ↓</span>
          </div>
        </div>
      )}
    </div>
  );
}
